### ISSUE TITLE
add an api check in the main java webapp screen

### ISSUE THREAD

**Issue by chanezon** [dockersamples/hybrid-app#10]
right now to test that the app is connected to the api, you need to create a user, then login.
Add a line at the top of the main screen that displays the number of users in the system or something that can be pulled from the api, or an error message if the api cannot be reached. so you know right away if the system is healthy.

**Comment by indcoder** [comment]
One suggestion : From the published end point/java-web , we need a way for the front signup page to depict that it is connected to
1) Java database [swarm]
2) dotnet api [swarm]and 
3) dotnet api core [Kubernetes]
 
This will provide a quick visual validation. Right now we see only the same signup page for all three and that validates only the web service is up and to not what it is connected to the backend.
