### ISSUE TITLE
Tweet at each stage of the workshop

### ISSUE THREAD

**Issue by indcoder** [dockersamples/hybrid-app#12]
In the previous version of the workshop, when an attendee completed the Linux part of the workshop successfully, he was provided a page that could be tweeted from the Linux container and the same was also when the Windows container of the workshop was completed. This served as useful gateway markers of the workshop and also fostered a sense of achievement for the attendee and s/he could let the world know about it.

**Comment by spara** [comment]
That's a great idea! I'll try to get that feature in by Dockercon.
