### ISSUE TITLE
README.md should explain the app and how to use it

### ISSUE THREAD

**Issue by chanezon** [dockersamples/hybrid-app#3]
https://github.com/dockersamples/hybrid-app/blob/master/README.md
should have an explanation for 3 versions with architecture diagrams.
and instructions for how to develop and deploy using compose and docker stack deploy.

**Comment by ManoMarks** [comment]
We have a README.md in each directory, but I think the app should have an over-all README.md that shows how it works. @spara can you pull that together?

**Comment by chanezon** [comment]
Nice, thank you @spara !
